version: "2"
services:
  covid19:
    container_name: covid19
    image: nobudev/covid19:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8005:8888"
      - "10005:22"
    volumes:
      - "~/GitHub/Covid-19:/home/dev/projects/covid19"
